services:
  # Backend API Service
  - type: web
    name: acapal-events-api
    env: node
    buildCommand: cd api && npm install
    startCommand: cd api && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        value: rediss://default:ATOAAAIjcDE3YTNkNmUxNjZlZDI0OGIwODI2MjUxNTM5MDUwZWQyYnAxMA@logical-mosquito-13184.upstash.io:6379
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/events
    autoDeploy: true
    plan: free
    numInstances: 1

  # Frontend Expo Service
  - type: web
    name: acapal-events-frontend
    env: node
    buildCommand: |
      npm install
      npm install -g expo-cli
      npx expo export --platform web
    startCommand: npx serve dist --single
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://acapal-events-api.onrender.com
      - key: EXPO_PUBLIC_API_URL
        value: https://acapal-events-api.onrender.com
    healthCheckPath: /
    autoDeploy: true
    plan: free
    numInstances: 1

